### ISSUE TITLE
KITTI

### ISSUE THREAD

**Issue by MartinHahner88** [mit-han-lab/pvcnn#1]
[this is no issue, just a question]

**Thanks a lot for releasing your code!**

I searched for the keyword _kitti_ in your code, but there were _0_ hits.

In your paper, you also trained and evaluated on KITTI. 
Will you also release code to reproduce those experiments?

Again, thanks so much for contributing to the community by releasing your code!

**Comment by memoiry** [comment]
+1, it seems that the original frustum-pointnets is implemented in tensorflow.

**Comment by synxlin** [comment]
Hi, we have released the PyTorch code for Frustum PointNets and Frustum PVCNN Efficient on the KITTI dataset.
