### ISSUE TITLE
NaN or Inf found in input tensor

### ISSUE THREAD

**Issue by Napoleongl** [mit-han-lab/pvcnn#10]
Hi!
Thanks for your great work and for releasing your code!
I'm trying to run the S3DIS model on an outdoors dataset that contains one more feature and four less classes than S3DIS (i.e. 7 and 9 respectively). However, when running either pvcnn or pvcnn2, I get a warning in the terminal `NaN or Inf found in input tensor` after 5-120 iterations. The accuracy reported is also very low (like .08%) and everything seems to get sent to the largest class (very unbalanced dataset, but that will be handled later). This does not happen when running your Pointnet implementation.

I have looked through the h5-files (and the .npy-files) and none of them contain neither NaN or Inf. I have changed the number of extra features and dataset classes everywhere I have found them. 
Any suggestions on where else to look or what could cause the issue? Could it have to do with the conversion from .npy-files to h5-files? Or does it have to do with the voxelisation somehow, perhaps my voxels are too small or big since the scale of my data is different than S3DIS.

**Comment by synxlin** [comment]
Hi, @Napoleongl. 

Would you mind posting the complete warning information?

The first step is to figure out which tensor becomes NaN or Inf. Sometimes it may come from the normalization in the Voxelization (e.g. Line 20 in https://github.com/mit-han-lab/pvcnn/blob/master/modules/voxelization.py). 

If that is the case, you may need to set "eps" to some constant like 1e-15 (e.g., Line 17 in https://github.com/mit-han-lab/pvcnn/blob/master/models/kitti/frustum/box_estimation/pointnet.py).

**Comment by Napoleongl** [comment]
Thank you very much @synxlin ! 
Actually, the informaiton posted is all the warning I get (apart from at which iteration we are which may vary slightly from run to run).
Your suggestion seems to have done the trick though and the models now run.
