### ISSUE TITLE
RuntimeError while building extension '_pvcnn_backend'

### ISSUE THREAD

**Issue by DulinkLu** [mit-han-lab/pvcnn#11]
Thanks for releasing your code~
I met a problem when I tried to train my model. An error occurs when I run this command:
```python train.py configs/shapenet/pointnet.py --devices 1,2```
And the error is like this:
```
Traceback (most recent call last):
  File "/root/anaconda3/envs/cv/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 949, in _build_extension_module
    check=True)
  File "/root/anaconda3/envs/cv/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:
......
RuntimeError: Error building extension '_pvcnn_backend': b'[1/7] c++ -MMD -MF grouping.o.d -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H
......
```
In my opinion it might be an error about compiling C and CUDA files. I searched on the internet and someone met similar problem said this is caused by the mismatched version of gcc and CUDA. Is it the origin of this problem? If so, can u tell me the gcc and CUDA version u used?
THANKS! :)

**Comment by synxlin** [comment]
Hi, @DulinkLu.

We are using:
OS: Ubuntu 18.04.1
PyTorch: >= 1.3
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Cuda compilation tools, release 10.2, V10.2.89
