### ISSUE TITLE
Two questions about the pvconv.py

### ISSUE THREAD

**Issue by linhaojia13** [mit-han-lab/pvcnn#13]
Hi, Thank you for your good works!
When I look into the pvconv.py, I noticed that there is a parameter ‘with_se’ which is set 'Fasle' defaultly and control the recall of class ‘SE3d’. Can you tell me what a role does ‘SE3d’ plays and when should we set the 'with_se' True?
Another, the voxel features and point features are fused by a plus operation, whicn can be seen from the codes below:

`fused_features = voxel_features + self.point_features(features)`

However, I think it is a natural idea to use a concatenation as the fusion manner. Could you tell me the practical or intuitive reasons to make such a choice?

**Comment by synxlin** [comment]
Hi, @linhaojia13.

1. `SE3d` works as the same as the squeeze-and-excitation layer in 2D CNN. Generally, PVCNN is able to outperform its backbone without the help of `SE3d'. However, when the width multiplier is very small (such as 0.125x), `SE3d` can help to improve the performance at very little computation cost. 

2. We did the ablation study on concatenation and add. Concatenation performs slightly worse than the add. Meanwhile, add can help reduce the feature map size which is more hardware friendly.

**Comment by linhaojia13** [comment]
Thank you for your patient reply!
