### ISSUE TITLE
about training on KITTI dataset

### ISSUE THREAD

**Issue by amiltonwong** [mit-han-lab/pvcnn#15]
Hi, @authors,

Could you also give an example command on how to train KITTI dataset? I only see the [example command](https://github.com/mit-han-lab/pvcnn#training) for training the S3DIS dataset.

THX!

**Comment by synxlin** [comment]
Hi, @amiltonwong. In general, to train a model, one can run

`python train.py [config-file] --devices [gpu-ids]`

For KITTI, you can run

`python train.py configs/kitti/frustum/pvcnne.py --devices 0`
`python train.py configs/kitti/frustum/pointnet.py --devices 0`
`python train.py configs/kitti/frustum/pointnet2.py --devices 0`
