### ISSUE TITLE
How can I training with original datasets?

### ISSUE THREAD

**Issue by crea397** [mit-han-lab/pvcnn#16]
How can I training with original datasets with PVCNN?

**Comment by synxlin** [comment]
Hi, @crea397. In general, to train a model, you can run,
```
python train.py [config-file] --devices [gpu-ids]
```

For example, to train PVCNN on S3DIS holding out Area 5, you can run
```
python train.py configs/s3dis/pvcnn/area5/c1.py --devices 0,1
```
