### ISSUE TITLE
Evaluate

### ISSUE THREAD

**Issue by Jacky-gsq** [mit-han-lab/pvcnn#17]
i have used my 2D detector to generate the "*frustum.pickle" file and put it into the "/pvcnn/data/kitti/frustum/frustum_data/".  Besides, the pvcnn.py was trained as your "ReadMe“.
But when i evaluate it throws the mistake as follows:
'''
/pvcnn# python train.py configs/kitti/frustum/pvcnne.py --devices 0 --evaluate
  File "train.py", line 23
    print(f'==> loading configs from {args.configs}')
                                                   ^
SyntaxError: invalid syntax
 '''
Could you help me for that?  And if i run "python train.py configs/kitti/frustum/pvcnne.py --devices 0 --evaluate" directly, whether the model will be evaluated by my "frustum_carpedcyc_val_rgb_detection.pickle"?   

These are very imporant and urgent for me，looking forward to your apply. Thanks a lot again!

**Comment by synxlin** [comment]
Hi, @Jacky-gsq. What's your training command? To evaluate, you just add `--evaluate` after your training command. The error you showed is caused by missing the config file path.

To evaluate trained models, you can do inference by running:
```
python train.py [config-file] --devices [gpu-ids] --evaluate
```
