### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by Jacky-gsq** [mit-han-lab/pvcnn#18]
How can i test the trained model on my own data, which partly was prosessed to  frustum-data by 2D detectors like "frustum_carpedcyc_rgb_detection.pickle"?

Thank you!

**Comment by synxlin** [comment]
Hi, @Jacky-gsq.

To train or test models on your own data, you should have pickles under `/data/kitti/frustum/frustum_data` if you don't plan to change the `configs.dataset.root` in [config file](https://github.com/mit-han-lab/pvcnn/blob/master/configs/kitti/frustum/__init__.py).

To train the model on your own data, you should have `frustum_carpedcyc_train.pickle` and to evaluate the model on your own data, you should have `frustum_carpedcyc_val_rgb_detection.pickle`. Please see Line 70 to 90 [here](https://github.com/mit-han-lab/pvcnn/blob/master/datasets/kitti/frustum.py) to check the content in pickle file.

**Comment by Jacky-gsq** [comment]
@synxlin Thank you first!
if i test the model on my own dataset, whether need to change the idx_path to "/data/kitti/image_sets/test.txt"?

**Comment by synxlin** [comment]
You have to provide ground truth files under `data/kitti/ground_truth` as `training/label_2 data/kitti/` of `data_object_label_2.zip` downloaded from KITTI website. You also have to provide split of val by replacing `/data/kitti/image_sets/val.txt`.

**Comment by Jacky-gsq** [comment]
Thank you very much!
