### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by ShettyHarapanahalli** [mit-han-lab/pvcnn#19]
I am interested to use this for a custom dataset collected using a 3D camera (ex- Intel Real sense) can you please point me resources to build dataset and train the same.

**Comment by geothan** [comment]
I'm interested in to use a custom dataset, have you found a solution, till now?

**Comment by wangyidong3** [comment]
looking forward some clue or any suggestions.

**Comment by zhijian-liu** [comment]
Hi all, I think as long as the dataset can be represented as a set of points, each with coordinates and features. It should be easy to use the current codebase to train the model.
