### ISSUE TITLE
test error.

### ISSUE THREAD

**Issue by amiltonwong** [mit-han-lab/pvcnn#2]
Hi, authors,

After input the command `python train.py --devices 0 --evaluate --configs.train.best_checkpoint_path /data/code11/pvcnn/trained_models/s3dis.pvcnn.area5.pth.tar`, I got the following error : 

```
(pytorch1.0) root@milton-ThinkCentre-M93p:/data/code11/pvcnn# python train.py --devices 0 --evaluate --configs.train.best_checkpoint_path /data/code11/pvcnn/trained_models/s3dis.pvcnn.area5.pth.tar
==> loading configs from ['/data/code11/pvcnn/trained_models/s3dis.pvcnn.area5.pth.tar']
Traceback (most recent call last):
  File "train.py", line 213, in <module>
    main()
  File "train.py", line 52, in main
    configs = prepare()
  File "train.py", line 24, in prepare
    configs.update_from_modules(*args.configs)
  File "/data/code11/pvcnn/utils/config.py", line 118, in update_from_modules
    importlib.import_module(module)
  File "/root/anaconda3/envs/pytorch1.0/lib/python3.6/importlib/__init__.py", line 121, in import_module
    raise TypeError(msg.format(name))
TypeError: the 'package' argument is required to perform a relative import for '.data.code11.pvcnn.trained_models.s3dis.pvcnn.area5.pth.tar'

```

Is there something wrong with the command I used or something wrong with the relative import?

THX!

**Comment by synxlin** [comment]
Hi,  you have to specify a config file to build the model before loading the checkpoint:
```
python train.py [config file in configs/] --devices [gpu id] [other options]
```

Please run the following command,
```
python train.py configs/s3dis/pvcnn/area5.py --devices 0 --evaluate --configs.train.best_checkpoint_path /data/code11/pvcnn/trained_models/s3dis.pvcnn.area5.pth.tar
```

**Comment by amiltonwong** [comment]
Hi, @synxlin ,

Thanks for your reply. I use the command your mentioned:
`python train.py configs/s3dis/pvcnn/area5.py --devices 0 --evaluate --configs.train.best_checkpoint_path /data/code11/pvcnn/trained_models/s3dis.pvcnn.area5.pth.tar`. However, I got this [error](https://gist.github.com/amiltonwong/cd2e9ec4f5cab10e8ec317c1c4c05f78). It seems the error comes from c++ extention or Ninja package.

My system is pytorch 1.0 and Ninja-1.9.0 installed.

Any suggestion to solve this issue?

THX!

**Comment by synxlin** [comment]
Hi, You need Pytorch >= 1.3. I will update the README.md.
