### ISSUE TITLE
Results visualization

### ISSUE THREAD

**Issue by Jacky-gsq** [mit-han-lab/pvcnn#20]
i'm sorry for consulting you again and angin!
Could you tell me how can i visualize the 3D detection results? or how can i change your code to realize that?
Thank you very much!

**Comment by benjaminkelenyi** [comment]
> i'm sorry for consulting you again and angin!
> Could you tell me how can i visualize the 3D detection results? or how can i change your code to realize that?
> Thank you very much!

Hello @Jacky-gsq, do you managed to visualize the 3D detection results?

**Comment by zhijian-liu** [comment]
I think you can visualize the segmentation results similar to the one in https://colab.research.google.com/github/mit-han-lab/e3d/blob/master/tutorial/e3d.ipynb.

**Comment by Hao-HUST** [comment]
> I think you can visualize the segmentation results similar to the one in https://colab.research.google.com/github/mit-han-lab/e3d/blob/master/tutorial/e3d.ipynb.

But I cannot open the visualization file now.

**Comment by zhijian-liu** [comment]
The link has been updated: https://github.com/mit-han-lab/spvnas/blob/master/tutorial.ipynb.
