### ISSUE TITLE
3D prediction without groundtruth

### ISSUE THREAD

**Issue by Jacky-gsq** [mit-han-lab/pvcnn#21]
Hi, guys, now i have a raw dataset without groundtruth, and i just implement  the 3D prediction and save the result with prediction-box. 
Could you tell me how to change the conde to achieve that? Thanks a lot！

**Comment by zhijian-liu** [comment]
The code release in this repo is meant for reproducing the results of research papers.

We help users who have trouble using the code to reproduce results in the paper, but in general, we do not provide suggestions on other issues such as how to apply the method to a new task or dataset.
