### ISSUE TITLE
Running with CPU only 

### ISSUE THREAD

**Issue by roeisun** [mit-han-lab/pvcnn#23]
Hi , this is possible to run the pre-trained model without CUDA ? 
i want to generate the network graph to see the structure and the dimensions of the layer.
i just want to understand the inputs and dimensions. 

Thanks

**Comment by synxlin** [comment]
Hi, @roeisun. Currently, we only write the CUDA version of computing kernels, and thus it is impossible to run without CUDA.

**Comment by roeisun** [comment]
Thanks.
