### ISSUE TITLE
Pytorch 1.5.0 with error while buiding '_pvcnn_backend'

### ISSUE THREAD

**Issue by nicolexie** [mit-han-lab/pvcnn#24]
hi, thanks for the code!
'_pvcnn_backend' cannot be build when I  run it with pytorch 1.5.0.
then I install pytroch 1.4.0 and it is ok.
so is it a version issue?

**Comment by synxlin** [comment]
Hi, @nicolexie. Sorry for the late response. We're looking into this.

**Comment by nicolexie** [comment]
> Hi, @nicolexie. Sorry for the late response. We're looking into this.

Hi, there is something wrong with the backend.py running today.
so I doubt that it may be not the version issue.
the running infomation is as below and it stoped here
"Using /tmp/torch_extensions as PyTorch extensions root..."
 
and the solution for my problem is to remove the "lock" file in /tmp/torch_extensions/_pvcnn_backend/

I guess that last time when I reinstalled the pytorch, the file is removed at the same time.

I haven't figured out the real reason so far，sorry for jumping at conslusion last time.

**Comment by synxlin** [comment]
Thank you for notifying us. I will close the issue for now. Feel free to re-open if you have further problems.
