### ISSUE TITLE
The training code keeps running for a long time 

### ISSUE THREAD

**Issue by janismdhanbad** [mit-han-lab/pvcnn#25]
Hi synxlin,

Thanks for the repo!

I have prepared the s3dis data and running the following line 

`python train.py configs/s3dis/pvcnn/area5/c1.py --devices 0`

After I run this line, my code keeps running for a long time(been running for the last 7 hours) and shows no output. It seems like it is stuck somewhere cause doing `nvidia-smi` shows no GPU utilization. 

My command line looks like this:

```
(pvcnn) datumx@pop-os:~/data_science_experiments/3D_data/pvcnn$ python train.py configs/s3dis/pvcnn/area5/c1.py --devices 0

==> loading configs from ['configs/s3dis/pvcnn/area5/c1.py']
```

I would be grateful if someone could point me in the right direction.

**Comment by synxlin** [comment]
Hi, @janismdhanbad. What's your Pytorch version?

**Comment by janismdhanbad** [comment]
@synxlin , Thanks for the reply. Pytorch version 1.5 with Cuda 10.2 on ubuntu 18.04. I will change the version to 1.4 and try again, thanks for pointing that out.

**Comment by synxlin** [comment]
Hi, we are looking into the problems in Pytorch 1.5. Perhaps this issue #24 could help you.

**Comment by janismdhanbad** [comment]
Hi, it worked. I was playing with Pytorch and cudatool kit versions and it worked on Pytorch 1.4.0 along with cuda 10.1. Thanks!

**Comment by nicolexie** [comment]
hi, is the voxel_features right in the code:
voxel_features, voxel_coords = self.voxelization(features, coords)

I got all zeros elements

**Comment by cslxiao** [comment]
same problem with pytorch 1.6
