### ISSUE TITLE
About the voxelization code

### ISSUE THREAD

**Issue by zx19950617** [mit-han-lab/pvcnn#26]
Hi, @synxlin , thanks for your excellent work and  sharing! Now, I'm confused about:
1. the voxelization code in /modules/voxelization.py:
https://github.com/mit-han-lab/pvcnn/blob/578e899fa2b7b9a97b8878b21df1a092380aba16/modules/voxelization.py#L22
if self.normalize = False, what does this line of code mean?why add 1 and devide 2.0?

2. In addition, self.normalize seems to be equal to False in the available code https://github.com/mit-han-lab/pvcnn/blob/578e899fa2b7b9a97b8878b21df1a092380aba16/models/shapenet/pvcnn.py#L20 while True in the paper. 
I'd like to know whether the normalization is essential or optionally.

Looking forward to your reply , and any answer benefits me a lot!
Best regards!

**Comment by synxlin** [comment]
Hi, @zx19950617. 
For Question 1, after subtracting `mean`, `norm_coords` mostly lie in [-1, 1]. We shift the data range to [0, 1] via adding one and then dividing by 2.
For Question 2, the input coordinates of the ShapeNet dataset are already normalized after data preparation; and thus we don't need to normalize these coordinates in the model.

**Comment by zx19950617** [comment]
OK, thanks for your patient and timely reply!
