### ISSUE TITLE
''voxel_features'' ,output of self.voxelization(features, coords) are zeros

### ISSUE THREAD

**Issue by nicolexie** [mit-han-lab/pvcnn#27]
hi, I run as follows:
python train.py configs/shapenet/pvcnn/c0p25.py --device 2
 
and I found that in pvconv.py:
voxel_features, voxel_coords = self.voxelization(features, coords)
the voxel_features elements are alll zeros.

It seems that the _backend does not work, but the output format is right,
and backend is also build:
''Using /tmp/torch_extensions as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /tmp/torch_extensions/_pvcnn_backend/build.ninja...
Building extension module _pvcnn_backend...
ninja: no work to do.
Loading extension module _pvcnn_backend...''

**Comment by synxlin** [comment]
Hi, @nicolexie. I have fixed check API for PyTorch 1.5 and tried running the command. It should work now for PyTorch 1.5.

**Comment by nicolexie** [comment]
> Hi, @nicolexie. I have fixed check API for PyTorch 1.5 and tried running the command. It should work now for PyTorch 1.5.

Thanks for the reply.  I use PyTorch 1.3.0 recently.  The output format is right, but the values are all zeros, I have not figure out 
the reason.

**Comment by synxlin** [comment]
Hi, @nicolexie. 
I would recommend you to delete `_pvccn_backend` under /tmp/torch_extensions, and tried again. 
For Pytorch 1.3, the check API in [this file](modules/functional/src/utils.hpp) should be `AT_CHECK`, while `TORCH_CHECK` for Pytorch 1.5.

**Comment by nicolexie** [comment]
> Hi, @nicolexie.
> I would recommend you to delete `_pvccn_backend` under /tmp/torch_extensions, and tried again.
> For Pytorch 1.3, the check API in [this file](modules/functional/src/utils.hpp) should be `AT_CHECK`, while `TORCH_CHECK` for Pytorch 1.5.

I tried, pytorch 1.3 and1.5 both， but I got the same error

**Comment by nicolexie** [comment]
cuda 

> > Hi, @nicolexie.
> > I would recommend you to delete `_pvccn_backend` under /tmp/torch_extensions, and tried again.
> > For Pytorch 1.3, the check API in [this file](modules/functional/src/utils.hpp) should be `AT_CHECK`, while `TORCH_CHECK` for Pytorch 1.5.
> 
> I tried, pytorch 1.3 and1.5 both， but I got the same error

maybe cuda problem

**Comment by zx19950617** [comment]
Hi, @synxlin @nicolexie ! I met the same problem. 
voxel_features, voxel_coords = self.voxelization(features, coords)
voxel_features are alll zeros.

Confusedly, the program doesn't raise any warning and error.

My environments are as follows: 
pytorch 1.3.1
cuda 10.0
How do you solve this problem? Any suggestion will be appreciated a lot!

Best regards

**Comment by zx19950617** [comment]
Hi, @synxlin @nicolexie ! I met the same problem.
voxel_features, voxel_coords = self.voxelization(features, coords)
voxel_features are zeros.

Confusedly, the program doesn't raise any warning and error.

My environments are as follows:
pytorch 1.3.1
cuda 10.0
How do you solve this problem? Any suggestion will be appreciated a lot!

Best regards

**Comment by nicolexie** [comment]
> Hi, @synxlin @nicolexie ! I met the same problem.
> voxel_features, voxel_coords = self.voxelization(features, coords)
> voxel_features are zeros.
> 
> Confusedly, the program doesn't raise any warning and error.
> 
> My environments are as follows:
> pytorch 1.3.1
> cuda 10.0
> How do you solve this problem? Any suggestion will be appreciated a lot!
> 
> Best regards

I changed the cuda version, and 
My environments are as follows:
 pytorch 1.5
 cuda 10.0

**Comment by Pirazh** [comment]
Hi @nicolexie,

So did changing the CUDA version solved your problem entirely? right now I am using CUDA 11.6 and Pytorch 1.13 and I have the exact same issue, without giving any error, the code runs and produces an all zero tensor for the voxel volume despite that point cloud has non-zero features.

I am wondering if you tried the code with a more recent version of CUDA and Pytorch

**Comment by HLJT** [comment]
> 你好@nicolexie,
> 
> 现在更改 CUDA 版本是否解决了您的问题？现在我正在完全使用 CUDA 11.6 和 Pytorch 1.13，我遇到了几十个问题，没有给出任何错误，代码运行并为体素体积生成全零张量，点云具有非零特征。
> 
> 我想知道您是否使用 CUDA 和 Pytorch 的更新版本尝试过该代码

Hello, I also encountered the same problem as you. Did you solve it? I would be very grateful if you could reply.
