### ISSUE TITLE
offset values while creating data for S3DIS Dataset

### ISSUE THREAD

**Issue by janismdhanbad** [mit-han-lab/pvcnn#28]
Hi @synxlin , Thanks for the amazing repo!

I have a question on the following line,
https://github.com/mit-han-lab/pvcnn/blob/db13331a46f672e74e7b5bde60e7bf30d445cd2d/data/s3dis/prepare_data.py#L138,
I can see that there are two offset values for which the same file is iterated. This offset value shifts the minimum x, y, z with the respective values. I am unable to understand the implication of this on the training. If you could please point me in the right direction on this one. I am trying to use a custom dataset and trying to understand how to pick these offset values for the data. 

Also, while inferencing on the new test data, should I create two files out of one file for two given offset values? And then merge the output of two files into a single file to get the final predictions?

Thank you!

**Comment by kentangSJTU** [comment]
Hello,

The offsets variable controls the way we generate sliding windows (whether we start from minimum coordinates or minimum coordinates plus a half block size offset). We actually inherit this setting from PointCNN implementation. The reason why we use these offsets is that the border regions of sliding windows might not be processed properly if we have just zero offset (for example, a chair might be separated into two parts if it lies on the border).

On the test data, it is OK to generate sliding windows with one offset or two. The later is adopted by PointCNN and us, and achieves better performance.

Best,
Haotian
