### ISSUE TITLE
voxel_features, voxel_coords = self.voxelization(features, coords)

### ISSUE THREAD

**Issue by zx19950617** [mit-han-lab/pvcnn#29]
Hi, @synxlin !  Thanks for your excellent work and sharing! I met the problem shown as follow:
voxel_features, voxel_coords = self.voxelization(features, coords)
voxel_features are zeros.

It seems _backend doesn't work. out in the following code are zeroes.
https://github.com/mit-han-lab/pvcnn/blob/db13331a46f672e74e7b5bde60e7bf30d445cd2d/modules/functional/voxelization.py#L22

Confusedly, the program doesn't raise any warning and error.
Also, I tried the solution in https://github.com/mit-han-lab/pvcnn/issues/27#issuecomment-649232721 and removed the /tmp/torch_extensions/_pvcnn_backend, however, it didin't work.

My environments are as follows:
pytorch 1.3.1
cuda 10.0
How to solve this problem? Any suggestion will be appreciated a lot!

Best regards!

**Comment by synxlin** [comment]
Hi, @zx19950617.
For Pytorch 1.3, the check API in [this file](https://github.com/mit-han-lab/pvcnn/issues/modules/functional/src/utils.hpp) should be AT_CHECK, while TORCH_CHECK for Pytorch 1.5.
According to #27, it may be the CUDA version problem. Could you upgrade your CUDA version to at least 10.2?

**Comment by zx19950617** [comment]
Hi, @synxlin , thanks for your reply!
I couldn't upgrage my cuda version because the version of the nvidia driver is 410.104, which supports the newest version of  cuda is only 10.0. And sadly, I counldn't change the nvidai driver since the host is used for public deep learning server.

So, I'd like to search for a solution based on my current environment. Any other idea benefits me, thanks!

**Comment by zx19950617** [comment]
Hi, @synxlin , I have upgraded nvidia driver and cuda to 10.2. And my pytorch is 1.5.0.
However, this doesn't work for me. voxel_features are still all zeros with correct format. The program dosen't raise any warning and errors.
 I didn't know how to figure it out.

**Comment by Pirazh** [comment]
Hi, I am facing a similar issue right now, when I try to voxelize my point cloud with corresponding non-zero features coordinates, without throwing any issues, `F.avg_voxelize_forward(features, coords, resolution)` outputs all zero feature grid with the intended size. My CUDA version is 11.6 and I am using `pytorch 1.13`. I already removed files under the `torch_extension` directory but this did not help solving the issue either. I appreciate if you can let me know about a potential solution.
