### ISSUE TITLE
Where to get the appendix?

### ISSUE THREAD

**Issue by asurada404** [mit-han-lab/pvcnn#36]
Thanks for sharing the code.
You mentioned in the paper that more detail of the experiments can be found in the appendix.
Where can I get the appendix?

**Comment by zhijian-liu** [comment]
Hi,

Thanks for your interest in our work! The appendix can be found at https://papers.nips.cc/paper/8382-point-voxel-cnn-for-efficient-3d-deep-learning-supplemental.zip.

Best,
Zhijian

**Comment by asurada404** [comment]
Thanks a lot.
