### ISSUE TITLE
What is point feature?

### ISSUE THREAD

**Issue by siyuan2018** [mit-han-lab/pvcnn#38]
Hi, first thanks for having such a good work. I have a question regarding the paper/code since I want to use my customized dataset. 

What is feature mean? As in the code, the input is "features, coords". I can understand coords are the coordinates of each point, how about features? How to generate the feature from the point cloud data? Thanks!

**Comment by zhijian-liu** [comment]
For different datasets, the feature can be different: it can be surface normal, intensity, reflectance, or simply the coordinates.

**Comment by OswaldoBornemann** [comment]
Suppose I have a dataset, the dimension is `[batch_size, coor_dim + feature_dim, numbers_of_points]`. So i wonder which is correct based on the below two actions. (Ps, I would like to reconstruct both the coordinate and feature.)

The first is 
```
features = x[:, :, :]
coords = x[:, :3, :]
voxel_features, voxel_coords = self.voxelization(features, coords)
```

Or the second one
```
features = x[:, 3:, :]
coords = x[:, :3, :]
voxel_features, voxel_coords = self.voxelization(features, coords)
```
