### ISSUE TITLE
Cones Detection

### ISSUE THREAD

**Issue by Etshhh** [mit-han-lab/pvcnn#39]
Hey, thanks a lot for sharing your amazing work!
I came by this repo and it's paper through your [Driverless Autonomous Team](https://www.youtube.com/watch?v=WW9paispAW0&t=348s) video on YouTube.
I just want to ask if there are any  _LiDAR_ opensource datasets for training a model for **cones detection**, or if you'd be kind enough to share the one you used.
Also, assuming i have the dataset, does training PVCNN on an xyzi point cloud require configuring certain parameters or will it work by default. Thanks a lot for your time and effort.

**Comment by zhijian-liu** [comment]
There isn't any public dataset for cone detection currently. If you have the dataset, you might need to modify the code to make it a classification model as it's currently a segmentation model.
