### ISSUE TITLE
S3DIS Algined Version

### ISSUE THREAD

**Issue by honggudrnjs** [mit-han-lab/pvcnn#40]
Thanks for sharing your code :)
By the way, I have a question though.
Your data processing code implies that  you might use S3DIS dataset of aligned version right?
I see some projects use non-aligned version (standard one). 
Then, is there any reason for using aligned version?

**Comment by kentangSJTU** [comment]
Hello,

We use the aligned version for fair comparison with PointCNN.

Best,
Haotian
