### ISSUE TITLE
Change Voxel Resolution

### ISSUE THREAD

**Issue by CWanli** [mit-han-lab/pvcnn#41]
How can I increase the voxel resolution? For example, If I want to generate an 128x128x128 voxel, what should I do?  Can I just increase the "voxel_resolution_multiplier" parameter?

**Comment by zhijian-liu** [comment]
I think that might not work. You can change `blocks` at https://github.com/mit-han-lab/pvcnn/blob/db13331a46f672e74e7b5bde60e7bf30d445cd2d/models/shapenet/pvcnn.py#L10 where the third parameter in the tuple corresponds to the voxel resolution of each block.

**Comment by CWanli** [comment]
Thank you for the response!!

**Comment by CWanli** [comment]
Another question...
Would you please explain the meaning of other parameters in the tuple?

**Comment by CWanli** [comment]
I see. it is
out_channels, num_blocks, voxel_resolution

**Comment by Hao-HUST** [comment]
> I think that might not work. You can change `blocks` at
> 
> https://github.com/mit-han-lab/pvcnn/blob/db13331a46f672e74e7b5bde60e7bf30d445cd2d/models/shapenet/pvcnn.py#L10
> 
> where the third parameter in the tuple corresponds to the voxel resolution of each block.

Hi, will the prediction accuracy be beneficial by increasing the voxelization resolution, if the amount of lidar points in a frustum is dense and large enough? Do you have any suggestions about that?

**Comment by zhijian-liu** [comment]
Increasing the voxel resolution can be beneficial particularly when the input scale is large. But it also significantly affects the memory consumption. Therefore, it really depends on your application and the memory/latency constraint you have.
