### ISSUE TITLE
The pretrained models can't be found.

### ISSUE THREAD

**Issue by soccermom123** [mit-han-lab/pvcnn#48]
Hi, sorry to bother. It seems that the links to the pages of pretrained models cannot be found. Is it possible for you to provide the pretrained models? Thanks a lot.

**Comment by zhijian-liu** [comment]
Hi @soccermom123, I've just updated the README with the new download links. Please let me know if there are any questions. Thanks!

**Comment by soccermom123** [comment]
Thank you so much! @zhijian-liu
