### ISSUE TITLE
different implement time  with different size of dataset

### ISSUE THREAD

**Issue by Chichy210** [mit-han-lab/pvcnn#52]
I use pretrain model with kitti dataset. When I use dataset length 25392 ,the speed is 18 its/s.But we use  first 348 data with same dataset,the speed is much lower that only 5.43 its/s.I want to know what causes the speed difference.

**Comment by zhijian-liu** [comment]
The first few iterations could be slower because the GPU might not be sufficiently warmed up in this case. You could try to run a few dummy iterations to warm up before testing the latency.

**Comment by Chichy210** [comment]
Thank for your response!!
I have already test it, and it works.
