### ISSUE TITLE
HOW CAN I INSTALL TORCH WITH PY37 ON AGX XAVIER

### ISSUE THREAD

**Issue by s1mpleee** [mit-han-lab/pvcnn#53]
it seems that no available pytorch package was given with python3.7 on jetson right now

**Comment by zhijian-liu** [comment]
https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-9-0-now-available/72048

**Comment by s1mpleee** [comment]
> https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-9-0-now-available/72048

I still feel confused about should I build from source to install pytorch? or I can use the py36 wheel to build  it?
thank you!

**Comment by zhijian-liu** [comment]
You could try to use the wheel to install PyTorch. If it doesn't work, you could upgrade to the latest JetPack (https://developer.nvidia.com/embedded/jetpack), which has PyTorch pre-installed.
