### ISSUE TITLE
Training on ShapeNet part

### ISSUE THREAD

**Issue by HX-Tfd** [mit-han-lab/pvcnn#57]
Hi, thank you for the great work!

I'm using your pretrained models for downstream tasks and I have a question regarding training your version of PointNet on the ShapeNet Part dataset. 

How did you create the one-hot vectors indicating the shape categories? As in ```synsetoffset2category.txt``` (Airplane -> 1000...., Bag -> 0100...) or you did otherwise?

**Comment by kentang-mit** [comment]
I think your understanding is correct. This is the [code](https://github.com/mit-han-lab/pvcnn/blob/476715b113f9c119f88003729bc6475285f78819/datasets/shapenet.py#L23) we define the `shape_id` and we basically create the one-hot label based on `shape_id` [here](https://github.com/mit-han-lab/pvcnn/blob/476715b113f9c119f88003729bc6475285f78819/datasets/shapenet.py#L70).

**Comment by HX-Tfd** [comment]
> I think your understanding is correct. This is the [code](https://github.com/mit-han-lab/pvcnn/blob/476715b113f9c119f88003729bc6475285f78819/datasets/shapenet.py#L23) we define the `shape_id` and we basically create the one-hot label based on `shape_id` [here](https://github.com/mit-han-lab/pvcnn/blob/476715b113f9c119f88003729bc6475285f78819/datasets/shapenet.py#L70).

Thanks! My model seems to produce the expected behaviour now.
