### ISSUE TITLE
CAD Step files training

### ISSUE THREAD

**Issue by tomanick** [mit-han-lab/pvcnn#58]
Thanks for your sharing!
Nice work!
If I want to train my own dataset, those data are CAD step files.
How should I do data preprocessing ?
Changing those data to X,Y,Z,R,G,B ?

**Comment by zhijian-liu** [comment]
That's right. You should process each of your data into an `NxC` tensor, where `N` is the number of points and `C` is the feature size (which is 6 in your case).

**Comment by tomanick** [comment]
好的，謝謝
另外，想請問若點雲是比較稀疏的(比如：比較平滑和平坦的曲面，可能只有4個點雲(四個頂點)或10個點雲左右，但在複雜的曲面上，點雲分布較多)，在PVCNN中也能得到不錯的效果嗎?
還是在SPVNAS中 https://github.com/mit-han-lab/spvnas 能獲得比較好的效果?

**Comment by zhijian-liu** [comment]
PVCNN/SPVCNN is not designed for meshes. You need to first sample the point cloud from the mesh surface.

**Comment by tomanick** [comment]
OK. I got it.
Do you recommend libraries for sampling point cloud from mesh surface? 

Besides, the third parameter in tuples means voxel resolution, right?
![image](https://user-images.githubusercontent.com/37836335/160225351-73afecca-efec-48bf-91dc-701951d526cb.png)
Why the third parameters in the third and fourth blocks are None?
Those blocks do not need voxel for extracting features?

Thanks!

**Comment by zhijian-liu** [comment]
> Do you recommend libraries for sampling point cloud from mesh surface?

You could probably use something like https://github.com/PointCloudLibrary/pcl/blob/master/tools/mesh2pcd.cpp to sample point cloud from mesh surface.

> Those blocks do not need voxel for extracting features?

The third parameter is the voxel resolution in the voxel branch. We do not add the voxel branch for the third and fourth blocks due to the computation cost.

**Comment by tomanick** [comment]
> You could probably use something like https://github.com/PointCloudLibrary/pcl/blob/master/tools/mesh2pcd.cpp to sample point cloud from mesh surface.

OK. Thank you!

> The third parameter is the voxel resolution in the voxel branch. We do not add the voxel branch for the third and fourth blocks due to the computation cost.

OK. I get it. In addition, after I added new parameters in third and fourth blocks, I found that the model's performance became much better, even though it would need larger GPU memory.

Furthermore, I have converted step files to point clouds data successfully and I can train those data by PVCNN. 
It is worth mentioning that the results are good. （你們模型設計得很不錯👍）

Besides, I modified your dataset.py code for training custom dataset.
To help those people who want to train their own dataset, could I share the custom_dataset_loader.py on your GitHub page or on this issue page?
(請問我能在你們的Github issue 討論串這分享可以訓練自己數據集的dataset_loader.py嗎？ 如此一來，能讓你們的pvcnn project更完善，也能順便幫助那些想要訓練自己數據集的人)

Thanks!

**Comment by synxlin** [comment]
Your contribution is welcome. I suggest that you can fork our repo, add your dataset python file in the folder datasets/, update README.md to show how to use your code, and create a pull request.

**Comment by tomanick** [comment]
OK.
I will spend some time tidying up code and writing corresponding files.
After finishing those tasks, I will create a pull request to you.
Thanks!
