### ISSUE TITLE
can not import cpp files?

### ISSUE THREAD

**Issue by coallar** [mit-han-lab/pvcnn#59]
Hi, it is wrong when i train the command:
python3 train.py config/shapenet/pvcnn/c1.py
details coud be senn as below:

![image](https://user-images.githubusercontent.com/66529823/158990399-8c0daa86-0e1f-4b09-ad4d-f953fa410266.png)

**Comment by zhijian-liu** [comment]
This is probably due to the CUDA environment configuration. You could add these lines into your `.bashrc`:
```
export CUDA_PATH=/usr/local/cuda
export PATH=$CUDA_PATH/bin:$PATH
export LD_LIBRARY_PATH=$CUDA_PATH/lib64:$LD_LIBRARY_PATH
```
Remember to restart the terminal after this.
