### ISSUE TITLE
visualization and features 

### ISSUE THREAD

**Issue by sunghyun-nam** [mit-han-lab/pvcnn#61]
Hello. 
I'm studying for 3d semantic segmentation and I'm new in this field.
So I don't know what shoud I do for visualization using your model.
I also watched your advice and reference code related to visualization.
But I couldn't understand. 
Among the answers you gave, you were like "The visualization is based on the features from the last PVConv. You may color each point based on the relative L2-norm of its features from either point-based or voxel-based branches."
I know what you mean.. But I don't know how to use features.
Thanks in advance.

#54

**Comment by zhijian-liu** [comment]
Could you be more specific about your question? What do you want to visualize? Which step are you currently at? Thanks!

**Comment by sunghyun-nam** [comment]
> Could you be more specific about your question? What do you want to visualize? Which step are you currently at? Thanks!

I'd like to get the results in figure 6 
#54

I just do the process in README.md. 
There're just how to train(test, evaluate) model.
I want to visualize the results(features) from the model.

**Comment by zhijian-liu** [comment]
You could follow https://github.com/mit-han-lab/spvnas/blob/master/tutorial.ipynb to visualize the point cloud. For feature visualization, you need to generate the color based on the L2 feature norm.
