### ISSUE TITLE
CUDA kernel failed : an illegal memory access was encountered

### ISSUE THREAD

**Issue by XinYu-Andy** [mit-han-lab/pvcnn#63]
Hi,
I am using part of your code to build another program. However, I got the following error message when I ran the code on multiple GPUs. Any suggestions for solving this problem? 
Thanks.

CUDA kernel failed : an illegal memory access was encountered
void three_nearest_neighbors_interpolate(int, int, int, int, const float*, const float*, const float*, int*, float*, float*) at L:130 in /mnt/backup2/home/pgchen/lzz/diffusion/my_pvd/point_tool/modules/functional/src/interpolate/neighbor_interpolate.cu

**Comment by XinYu-Andy** [comment]
I have fixed this bug; It's a bug of MPI (not a part of this codebase).
I will close this issue.

**Comment by szy4017** [comment]
> I have fixed this bug; It's a bug of MPI (not a part of this codebase). I will close this issue.
Hi,
I meet the same problem.
I don't know how to fix the bug of MPI. Any suggestions for solving this problem?
Thanks.
