### ISSUE TITLE
How to convert custom op into tensorrt

### ISSUE THREAD

**Issue by BrotherStrong2** [mit-han-lab/pvcnn#64]
Thank you for your great job! 
When I try to convert pytorch model to tensorrt, there are some custom operations just like AvgVoxelization, furthest_point_sample hard to convert into tensorrt. Is there any suggestion or reference code for me? Thanks a lot.

**Comment by zhijian-liu** [comment]
It's not very easy to convert PVCNN to TensorRT. You probably need to register them as custom plugins in TensorRT.
