### ISSUE TITLE
Why use the code x = x - (minx + args.block_size / 2) in data/s3dis/prepare_data.py?

### ISSUE THREAD

**Issue by Ryz-dl** [mit-han-lab/pvcnn#65]
Could you please tell me the reason why you use the code  x = x - (minx + args.block_size / 2) in data/s3dis/prepare_data.py line 240?

**Comment by kentang-mit** [comment]
Hello @Ryz-dl,

That is to align with the design of PointCNN [here](https://github.com/yangyanli/PointCNN/blob/aa551ce5258dbf4f73db0d916826574f054dd3b9/data_conversions/prepare_s3dis_data.py#L65). Basically we want to divide the room into different sliding windows, and the sliding window can start from both (minx, miny) and (minx + block_size / 2, miny + block_size / 2). The latter might be more friendly for the boundary regions.

Best,
Haotian

**Comment by Ryz-dl** [comment]
> Hello @Ryz-dl,
> 
> That is to align with the design of PointCNN [here](https://github.com/yangyanli/PointCNN/blob/aa551ce5258dbf4f73db0d916826574f054dd3b9/data_conversions/prepare_s3dis_data.py#L65). Basically we want to divide the room into different sliding windows, and the sliding window can start from both (minx, miny) and (minx + block_size / 2, miny + block_size / 2). The latter might be more friendly for the boundary regions.
> 
> Best, Haotian

Thanks for your reply.It helped me a lot.
