### ISSUE TITLE
Two questions about feature extraction

### ISSUE THREAD

**Issue by houyongkuo** [mit-han-lab/pvcnn#66]
Hello, I am doing point cloud feature extraction recently, and I have two questions to ask:
1. I have obtained the high-dimensional features of the point cloud (eg. 32-dimensional), how to convert to 3-dimensional and get the visulization result similar to Figure 6 in the paper?
2. Regarding the fusion part, whether it is better to use additive fusion or cat fusion for the features obtained by the two branches, have you conducted experiments? Thanks

**Comment by zhijian-liu** [comment]
> I have obtained the high-dimensional features of the point cloud (eg. 32-dimensional), how to convert to 3-dimensional and get the visulization result similar to Figure 6 in the paper?

You can visualize the L2 norm of point features similar to the heatmap visualization.

> Regarding the fusion part, whether it is better to use additive fusion or cat fusion for the features obtained by the two branches, have you conducted experiments?

We tried both. The performance difference is marginal.

**Comment by zhijian-liu** [comment]
I'm closing this issue due to its inactivity. However, please feel free to reopen it if your problem persists.
