### ISSUE TITLE
error when running "from modules.functional.backend import _backend"

### ISSUE THREAD

**Issue by Carbord** [mit-han-lab/pvcnn#67]
Hello! When running " from modules.functional.backend import _backend ", I encounter the following error :

![S(}8ZFG7OM6R2B)Y_R4K7`J](https://user-images.githubusercontent.com/33995512/192755076-36661530-5fc4-4f0a-ab88-81b770652f56.png)

It may result from the wrong version. Can you provide the versions about the pytorch, nvcc, etc to run this repostory?

I am using pytorch 1.11. And the "ncvv -V" shows :
![7V{V ~SPM1Q_TS8_M5(YD20](https://user-images.githubusercontent.com/33995512/192755133-c84df379-3973-4219-991f-40cc7ee405a7.png)

while nvidia-smi shows :

![IXDO36BG50UI 5_U_KFA3M3](https://user-images.githubusercontent.com/33995512/192755041-c54cc8e6-168a-43f0-b4a5-64cdd81f2d13.png)

I wonder how to correctly run the code to import the corresponding functions about pvcnn_backend. Sincerely looking forward to your help.

**Comment by zhijian-liu** [comment]
Could you please post the full error message here? Thanks!

**Comment by stsan9** [comment]
Not the original poster but I had a similar error

> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1740, in _run_ninja_build
>     subprocess.run(
>   File "/opt/conda/lib/python3.9/subprocess.py", line 528, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/jovyan/work/PVD/train_generation.py", line 11, in <module>
>     from model.pvcnn_generation import PVCNN2Base
>   File "/home/jovyan/work/PVD/model/pvcnn_generation.py", line 6, in <module>
>     from modules import SharedMLP, PVConv, PointNetSAModule, PointNetAModule, PointNetFPModule, Attention, Swish
>   File "/home/jovyan/work/PVD/modules/__init__.py", line 1, in <module>
>     from modules.ball_query import BallQuery
>   File "/home/jovyan/work/PVD/modules/ball_query.py", line 4, in <module>
>     import modules.functional as F
>   File "/home/jovyan/work/PVD/modules/functional/__init__.py", line 1, in <module>
>     from modules.functional.ball_query import ball_query
>   File "/home/jovyan/work/PVD/modules/functional/ball_query.py", line 3, in <module>
>     from modules.functional.backend import _backend
>   File "/home/jovyan/work/PVD/modules/functional/backend.py", line 6, in <module>
>     _backend = load(name='_pvcnn_backend',
>   File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1144, in load
>     return _jit_compile(
>   File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1357, in _jit_compile
>     _write_ninja_file_and_build_library(
>   File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1469, in _write_ninja_file_and_build_library
>     _run_ninja_build(
>   File "/opt/conda/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1756, in _run_ninja_build
>     raise RuntimeError(message) from e
> RuntimeError: Error building extension '_pvcnn_backend': [1/14] c++ -MMD -MF bindings.o.d -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1014\" -isystem /opt/conda/lib/python3.9/site-packages/torch/include -isystem /opt/conda/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.9/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++14 -O3 -std=c++17 -c /home/jovyan/work/PVD/modules/functional/src/bindings.cpp -o bindings.o 
> FAILED: bindings.o 
> c++ -MMD -MF bindings.o.d -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1014\" -isystem /opt/conda/lib/python3.9/site-packages/torch/include -isystem /opt/conda/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.9/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++14 -O3 -std=c++17 -c /home/jovyan/work/PVD/modules/functional/src/bindings.cpp -o bindings.o 
> c++: fatal error: Killed signal terminated program cc1plus
> compilation terminated.
> [2/14] c++ -MMD -MF vox.o.d -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1014\" -isystem /opt/conda/lib/python3.9/site-packages/torch/include -isystem /opt/conda/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.9/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++14 -O3 -std=c++17 -c /home/jovyan/work/PVD/modules/functional/src/voxelization/vox.cpp -o vox.o 
> FAILED: vox.o 
> c++ -MMD -MF vox.o.d -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1014\" -isystem /opt/conda/lib/python3.9/site-packages/torch/include -isystem /opt/conda/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.9/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++14 -O3 -std=c++17 -c /home/jovyan/work/PVD/modules/functional/src/voxelization/vox.cpp -o vox.o 
> c++: fatal error: Killed signal terminated program cc1plus
> compilation terminated.
> [3/14] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1014\" -isystem /opt/conda/lib/python3.9/site-packages/torch/include -isystem /opt/conda/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.9/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' --compiler-bindir=/usr/bin/gcc-8 -std=c++14 -c /home/jovyan/work/PVD/modules/functional/src/sampling/sampling.cu -o sampling.cuda.o 
> [4/14] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1014\" -isystem /opt/conda/lib/python3.9/site-packages/torch/include -isystem /opt/conda/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.9/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' --compiler-bindir=/usr/bin/gcc-8 -std=c++14 -c /home/jovyan/work/PVD/modules/functional/src/interpolate/trilinear_devox.cu -o trilinear_devox.cuda.o 
> [5/14] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1014\" -isystem /opt/conda/lib/python3.9/site-packages/torch/include -isystem /opt/conda/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.9/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' --compiler-bindir=/usr/bin/gcc-8 -std=c++14 -c /home/jovyan/work/PVD/modules/functional/src/grouping/grouping.cu -o grouping.cuda.o 
> [6/14] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1014\" -isystem /opt/conda/lib/python3.9/site-packages/torch/include -isystem /opt/conda/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.9/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' --compiler-bindir=/usr/bin/gcc-8 -std=c++14 -c /home/jovyan/work/PVD/modules/functional/src/ball_query/ball_query.cu -o ball_query.cuda.o 
> [7/14] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1014\" -isystem /opt/conda/lib/python3.9/site-packages/torch/include -isystem /opt/conda/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.9/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' --compiler-bindir=/usr/bin/gcc-8 -std=c++14 -c /home/jovyan/work/PVD/modules/functional/src/interpolate/neighbor_interpolate.cu -o neighbor_interpolate.cuda.o 
> [8/14] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1014\" -isystem /opt/conda/lib/python3.9/site-packages/torch/include -isystem /opt/conda/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.9/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' --compiler-bindir=/usr/bin/gcc-8 -std=c++14 -c /home/jovyan/work/PVD/modules/functional/src/voxelization/vox.cu -o vox.cuda.o 
> [9/14] c++ -MMD -MF trilinear_devox.o.d -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1014\" -isystem /opt/conda/lib/python3.9/site-packages/torch/include -isystem /opt/conda/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.9/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++14 -O3 -std=c++17 -c /home/jovyan/work/PVD/modules/functional/src/interpolate/trilinear_devox.cpp -o trilinear_devox.o 
> [10/14] c++ -MMD -MF ball_query.o.d -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1014\" -isystem /opt/conda/lib/python3.9/site-packages/torch/include -isystem /opt/conda/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.9/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++14 -O3 -std=c++17 -c /home/jovyan/work/PVD/modules/functional/src/ball_query/ball_query.cpp -o ball_query.o 
> [11/14] c++ -MMD -MF sampling.o.d -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1014\" -isystem /opt/conda/lib/python3.9/site-packages/torch/include -isystem /opt/conda/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.9/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++14 -O3 -std=c++17 -c /home/jovyan/work/PVD/modules/functional/src/sampling/sampling.cpp -o sampling.o 
> [12/14] c++ -MMD -MF grouping.o.d -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1014\" -isystem /opt/conda/lib/python3.9/site-packages/torch/include -isystem /opt/conda/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.9/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++14 -O3 -std=c++17 -c /home/jovyan/work/PVD/modules/functional/src/grouping/grouping.cpp -o grouping.o 
> [13/14] c++ -MMD -MF neighbor_interpolate.o.d -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1014\" -isystem /opt/conda/lib/python3.9/site-packages/torch/include -isystem /opt/conda/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.9/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++14 -O3 -std=c++17 -c /home/jovyan/work/PVD/modules/functional/src/interpolate/neighbor_interpolate.cpp -o neighbor_interpolate.o 
> ninja: build stopped: subcommand failed.

Interestingly if I run the code again after it fails the first time, it'll start working.

Here's some additional information:
Dockerfile:

> FROM gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp:54ef7146
> 
> LABEL maintainer="Steven Tsan <stsan@ucsd.edu>"
> 
> USER root
> 
> RUN apt-get update && \
>     apt-get install -y vim
> 
> RUN pip install jetnet \
>     pip install mplhep
> 
> RUN echo 'export CUDA_HOME=/usr/local/cuda' >> ~/.bashrc && \
>     echo 'export PATH=${CUDA_HOME}/bin:${PATH}' >> ~/.bashrc && \
>     echo 'export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:$LD_LIBRARY_PATH' >> ~/.bashrc && \
>     source ~/.bashrc
> 
> RUN pip install matplotlib \
>                 tqdm \
>                 open3d \
>                 trimesh \
>                 scipy \
>                 Ninja
> 
> RUN apt-get --yes install build-essential
> RUN apt-get --yes install g++-8

nvcc --version
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2021 NVIDIA Corporation
> Built on Mon_Oct_11_21:27:02_PDT_2021
> Cuda compilation tools, release 11.4, V11.4.152
> Build cuda_11.4.r11.4/compiler.30521435_0

torch version 1.11.0

nvidia-smi
<img width="681" alt="Screen Shot 2022-11-05 at 12 13 27 AM" src="https://user-images.githubusercontent.com/42155174/200107677-d647097d-e03c-4ad3-a8bd-e56efae99b53.png">

**Comment by stsan9** [comment]
Previous error occurred on 2080-Ti. Saw the same on a 1080-Ti. For some reason it hasn't occurred for 3000 series and other GPU's like V100s.

**Comment by zhijian-liu** [comment]
The error is triggered by `c++: fatal error: Killed signal terminated program cc1plus`. Could you maybe check if it's due to the memory size?

**Comment by FengLoveBella** [comment]
@zhijian-liu I encounter the question of "No module named '_pvcnn_backend' when I try to run this code. My system is
 Ubuntu18.04, Cuda is 10.1, Pytorch is 1.4.0. Also, I tried Ubuntu 18.04 cuda 10.2, pytorch 1.7 still have this problem. The GPU memory is 24G.


![Screenshot from 2022-12-16 16-22-12](https://user-images.githubusercontent.com/11606333/208055139-9a5e3b25-0741-46d8-92e0-8477835cd216.png)

**Comment by FengLoveBella** [comment]
@zhijian-liu Thank you for you code and idea, very good.

**Comment by zhijian-liu** [comment]
Could you maybe add `verbose=True` to https://github.com/mit-han-lab/pvcnn/blob/db13331a46f672e74e7b5bde60e7bf30d445cd2d/modules/functional/backend.py#L6?

**Comment by FengLoveBella** [comment]
I tried to add the code verbose=True to the backend.py file, however, the error is still the same.
![image](https://user-images.githubusercontent.com/11606333/208225387-d63830cf-9295-4c81-97d2-8e9796e5b839.png)

**Comment by zhijian-liu** [comment]
Could you maybe directly import this file and let me know if there is any warning message?

**Comment by FengLoveBella** [comment]
@zhijian-liu When I tried to import these files directly, the error was the same. "ImportError: No module named '_pvcnn_backend'".

**Comment by zhijian-liu** [comment]
Could you do `python modules/functional/backend.py`?

**Comment by FengLoveBella** [comment]
@zhijian-liu I have already solved this problem, thank you. When I reboot the computer, the code is okay now. Come again, thank you.
