### ISSUE TITLE
About voxelization

### ISSUE THREAD

**Issue by SkyeFromKindergarten** [mit-han-lab/pvcnn#7]
Thanks for your work~ 
I'm puzzled about the result of voxelization. My questions are as follows:
1) What is the point features {fk} ? Is it the corrdinates? or it can be like rgb information?
2) What is the result of voxelization looks like? Is it in domain[0,1] or ..?

Looking for your reply, and best regards.

**Comment by synxlin** [comment]
Please refer to the voxelization Python code [here](https://github.com/mit-han-lab/pvcnn/blob/master/modules/voxelization.py) and CUDA code [here](https://github.com/mit-han-lab/pvcnn/blob/master/modules/functional/src/voxelization/vox.cu).

0. Voxelization means to voxelize the XYZ-space. Points of different XYZ coordinates may fall into the same voxel grid. We average the features of the points in the same grid as the feature of the grid.
1. Point features can be RGB information (for the first layer) or activations of MLP/Conv (for the following layers). It can also include coordinates, depending on your design choice.
2. The result of Voxelization python module [here](https://github.com/mit-han-lab/pvcnn/blob/master/modules/voxelization.py) is a tuple:
    - a feature tensor with the size of B x C x R x R x R, where B is the batch size, C is the #channels, R is the voxelization resolution.
    - a "voxelized" co-ordinates tensor (`norm_coords` in the code) with the size of B x 3 x P, where B is the batch size, P is the #points. Note the returned co-ordinates are the floating-point numbers in [0, R) for sake of backward, and they require `round()` to convert to actual voxelized co-ordinates made of the integer numbers in [0, R) (`vox_coords` in the code).

**Comment by SkyeFromKindergarten** [comment]
Thanks for your patient reply, I get my answer. I used binary representation in my work where 1 for occupied voxels and 0 for empty voxels, it seems to have a low performance. So I want to redesign it.
From your explaination, I think you use the average features(features extracted from RGB/coordinates) to 'fill' every voxel in B x C x R x R x R, am I right?

**Comment by synxlin** [comment]
Hi, @SkyeFromKindergarten. You are right. We average the features of the points in **the same grid** as the feature of the grid. If there are no points in the grid, then its feature will be zeros.

**Comment by SkyeFromKindergarten** [comment]
Thanks again :)
