### ISSUE TITLE
Some issues about feature propessing.

### ISSUE THREAD

**Issue by JudgeLJX** [mit-han-lab/pvcnn#70]
Hi,

Thanks for your paper. Could you please give me some ideas about my confusion?

Firstly, about the [ xyz in block + rgb + normalized xyz ] , the normalized xyz is normalized according to the xyz in block, or the orginal xyz. 

Secondly, why you use the [ xyz in block + rgb + normalized xyz ] as inputs, I check the code, and it seems that you just utilize the xyz in block to voxelize and devoxelize. So why still need normalized xyz as input, is that means you make use of the normalized xyz as a part of features?

Thirdly, what happens if I change the coordinates value when I devoxelize [B,C,R,R,R] features? Will it generated a point feature corresponding to the changing?

Best Regards

**Comment by zhijian-liu** [comment]
Your understanding is correct. Only the coordinates within the block are used for voxelization. All the other dimensions are features.

**Comment by JudgeLJX** [comment]
Thanks for your reply.

There is still one thing that confused me, will the parameters of voxelization and devoxelization join the backward propagation and update parameters?

**Comment by zhijian-liu** [comment]
Both voxelization and devoxelization are parameter-free. But they are both differentiable so that means the loss can be propagated through them.

**Comment by JudgeLJX** [comment]
Thank you so much!
