### ISSUE TITLE
Data Pre processing Issue.

### ISSUE THREAD

**Issue by JudgeLJX** [mit-han-lab/pvcnn#71]
Hi,

I found in the data pre-process, when generating zero_0.h5 file from xyrgb, label.npy, there will be some 0 points in the h5 file, how to these 0 points, and make sure they will not be included in the training process?

And what's the mean of the grid size = 0.03? 

Many thanks for your time.

Judge

**Comment by JudgeLJX** [comment]
HI , 
I found there are data num and split to full in h5 file, that should be the reason.

I am still confused about grid size = 0.03. how to define this number , and how it works?  
And if the data xyz not in [0,1] , can we still use this number to uniform sample?

Thanks a lot.

**Comment by kentang-mit** [comment]
Hi @JudgeLJX,

We use the `grid_size` defined by [PointCNN](https://github.com/yangyanli/PointCNN/blob/91fde862b1818aec305dacafe7438d8f1ca1d1ea/data_conversions/prepare_s3dis_data.py) in this project for fair comparison. The purpose of this parameter is to make sure the number of points within a cube with size `grid_size` will be roughly the same. If xyz is not in [0, 1], we can still use this number to uniform sample the output. However, note that if the data is very sparse (say, in the extreme case, the closest distance between each 2 points is larger than 0.03m), we may want to increase `grid_size` accordingly.

Best,
Haotian

**Comment by JudgeLJX** [comment]
Hello,

Many thanks for your explanation, 

By the way, in your method, you convert the XYZ into a block with size (1.5,1.5, z), but when I check the data, there are some values out of range (-0.75,0.75), why did this happen? And could you tell me if this influence somehow?

Best 

Judge

**Comment by kentang-mit** [comment]
Good question. I think this is because we have two "offset"s in the code. For offset = "zero", the values should be in the range of (0.0, 1.5, z). For offset = "half", (-0.75, 0.75) is the coordinate range.
