### ISSUE TITLE
Can I use just one step of voxelization and devoxelization operator to voxelize and devoxelize the point cloud?

### ISSUE THREAD

**Issue by OswaldoBornemann** [mit-han-lab/pvcnn#74]
Can I use just one step of voxelization and devoxelization operator to voxelize and devoxelize the point cloud? Just like below

```
voxelize_ops = Voxelization(resolution=32,
                                         normalize=True,
                                         eps=0)
features = x
coords = x[:, :3, :]
voxel_x, voxel_coords = self.voxelize_ops(features, coords)
x = F.trilinear_devoxelize(voxel_x,
                                   voxel_coords,
                                   32,
                                   self.training) 
```

**Comment by zhijian-liu** [comment]
Yes, you can voxelize and devoxelize the point cloud using the API we provided.

**Comment by HLJT** [comment]
> Can I use just one step of voxelization and devoxelization operator to voxelize and devoxelize the point cloud? Just like below
> 
> ```
> voxelize_ops = Voxelization(resolution=32,
>                                          normalize=True,
>                                          eps=0)
> features = x
> coords = x[:, :3, :]
> voxel_x, voxel_coords = self.voxelize_ops(features, coords)
> x = F.trilinear_devoxelize(voxel_x,
>                                    voxel_coords,
>                                    32,
>                                    self.training) 
> ```
Can I ask if you implemented this way and got voxelized features
