### ISSUE TITLE
Pretrained Models Page Not Found

### ISSUE THREAD

**Issue by wqdong8** [mit-han-lab/pvcnn#75]
hi,
ShapeNet pretrained model link shows that  “The page you are looking for doesn't exist or has been moved”, Can you provide a usable download address?

**Comment by zhijian-liu** [comment]
Please use `hanlab18.mit.edu` in place of `hanlab.mit.edu` in the link as a temporary solution.

**Comment by nargesghv** [comment]
Hello,

I want to predict my custom data set for pvcnn scan you give me the reshape
I should do before inserting my dataset to model?

**Comment by wqdong8** [comment]
Thanks!
