### ISSUE TITLE
Voxel features are all zero

### ISSUE THREAD

**Issue by HLJT** [mit-han-lab/pvcnn#76]
voxel_features, voxel_coords = self.voxelization(features, coords)

right now I am using CUDA 11.3 and Pytorch 1.12 and I have the exact issue, without giving any error, the code runs and produces an all zero tensor for the voxel volume despite that point cloud has non-zero features.

I am wondering if you tried the code with a more recent version of CUDA and Pytorch

**Comment by zhijian-liu** [comment]
We haven't tried the code with the latest CUDA and PyTorch. Could you try out the older CUDA and PyTorch to see whether that works? Thanks!

**Comment by HLJT** [comment]
I am so glad to receive your reply. As you said, I have also tried pytorch1.5 and cuda10.2, and the API is torch check, but the problem still hasn't been solved. Can you guess where the problem might be?

**Comment by HLJT** [comment]
At the beginning, I didn't know that the voxels before avg were all 0, and I tested the model trained in this case, and it was strange that the classification IOU was normal, ranging from about 70-95%. Can you have a reasonable explanation?
