### ISSUE TITLE
ImportError: DLL load failed while importing _pvcnn_backend: 找不到指定的模块。

### ISSUE THREAD

**Issue by Cocktail-salad** [mit-han-lab/pvcnn#77]
Hello, I encountered the following problems while training the model:

ImportError: DLL load failed while importing _pvcnn_backend: The specified module was not found.

The code is:

python train.py configs/s3dis/pvcnn/area5/c1.py --devices 0

The environment setup and data preparation are all done (pretrained Modeals skipped).

I'm sorry to bother you, but what is my problem and how should I solve it?

**Comment by zhijian-liu** [comment]
Could you please try reconfigure the environment in Docker? Let us know if the error still persists. Thanks!

**Comment by nargesghv** [comment]
> Could you please try reconfigure the environment in Docker? Let us know if the error still persists. Thanks!

You should check the requirements with your pytorch version and cuda, and run the code on docker with an isolated environment.
