### ISSUE TITLE
vox_coords = torch.round(norm_coords).to(torch.int32)

### ISSUE THREAD

**Issue by PhantomRing** [mit-han-lab/pvcnn#79]
About these two lines of code:
```
norm_coords = torch.clamp(norm_coords * self.r, 0, self.r - 1)
vox_coords = torch.round(norm_coords).to(torch.int32)
```
The range of norm_coords should be [0,1], so if self.r =2, the range of norm_coords will be [0,2]. Then, vox_coords will change the number of [0,0.5] to 0 and the number of [0.5,2] to 1, resulting in uneven voxelization.
Is there something wrong with my understanding?

**Comment by zhijian-liu** [comment]
If `self.r = 2`, then the range of `norm_coords` will be `[0,1]` instead of `[0,2]`.
