### ISSUE TITLE
Visualizations or evaluation results 

### ISSUE THREAD

**Issue by maryumjam** [mit-han-lab/pvcnn#8]
Hi guys I wanna know if you have any module to visualize or save the results for evaluation? It will be great if you can share it.

**Comment by KangchengLiu** [comment]
Also interested in result saving and visualization modules.

**Comment by baifanxxx** [comment]
Hi,
Can you provide visualization of the results? I think this will be very useful.

**Comment by benjaminkelenyi** [comment]
Hello guys @maryumjam, @KangchengLiu, @baifanxxx.
Do you managed to visualize the 3D detection results?

**Comment by zhijian-liu** [comment]
I think you can visualize the segmentation results similar to the one in https://colab.research.google.com/github/mit-han-lab/e3d/blob/master/tutorial/e3d.ipynb.
