### ISSUE TITLE
nvcc error   : 'cudafe++' died with status 0xC00000FD (STACK_OVERFLOW)

### ISSUE THREAD

**Issue by Xtian-hub** [mit-han-lab/pvcnn#80]
thanks for all. this issue as follows, make me do not know how to solve it. please help me.
(py37) C:\Users\17342>python G:\multi-obj\data\CNN\pvcnn-master\pvcnn-master\train.py configs/s3dis/pvcnn/area5/c1.py --devices 0,1
==> loading configs from ['configs/s3dis/pvcnn/area5/c1.py']
Traceback (most recent call last):
  File "F:\Anaconda\envs\py37\lib\site-packages\torch\utils\cpp_extension.py", line 1069, in _build_extension_module
    check=True)
  File "F:\Anaconda\envs\py37\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\multi-obj\data\CNN\pvcnn-master\pvcnn-master\train.py", line 266, in <module>
    main()
  File "G:\multi-obj\data\CNN\pvcnn-master\pvcnn-master\train.py", line 79, in main
    configs = prepare()
  File "G:\multi-obj\data\CNN\pvcnn-master\pvcnn-master\train.py", line 24, in prepare
    configs.update_from_modules(*args.configs)
  File "G:\multi-obj\data\CNN\pvcnn-master\pvcnn-master\utils\config.py", line 113, in update_from_modules
    importlib.import_module(module)
  File "F:\Anaconda\envs\py37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "G:\multi-obj\data\CNN\pvcnn-master\pvcnn-master\configs\s3dis\pvcnn\__init__.py", line 3, in <module>
    from models.s3dis import PVCNN
  File "G:\multi-obj\data\CNN\pvcnn-master\pvcnn-master\models\s3dis\__init__.py", line 1, in <module>
    from models.s3dis.pointnet import PointNet
  File "G:\multi-obj\data\CNN\pvcnn-master\pvcnn-master\models\s3dis\pointnet.py", line 4, in <module>
    from models.utils import create_pointnet_components, create_mlp_components
  File "G:\multi-obj\data\CNN\pvcnn-master\pvcnn-master\models\utils.py", line 5, in <module>
    from modules import SharedMLP, PVConv, PointNetSAModule, PointNetAModule, PointNetFPModule
  File "G:\multi-obj\data\CNN\pvcnn-master\pvcnn-master\modules\__init__.py", line 1, in <module>
    from modules.ball_query import BallQuery
  File "G:\multi-obj\data\CNN\pvcnn-master\pvcnn-master\modules\ball_query.py", line 4, in <module>
    import modules.functional as F
  File "G:\multi-obj\data\CNN\pvcnn-master\pvcnn-master\modules\functional\__init__.py", line 1, in <module>
    from modules.functional.ball_query import ball_query
  File "G:\multi-obj\data\CNN\pvcnn-master\pvcnn-master\modules\functional\ball_query.py", line 3, in <module>
    from modules.functional.backend import _backend
  File "G:\multi-obj\data\CNN\pvcnn-master\pvcnn-master\modules\functional\backend.py", line 8, in <module>
    sources=[os.path.join(_src_path,'src', f) for f in [
  File "F:\Anaconda\envs\py37\lib\site-packages\torch\utils\cpp_extension.py", line 683, in load
    is_python_module)
  File "F:\Anaconda\envs\py37\lib\site-packages\torch\utils\cpp_extension.py", line 869, in _jit_compile
    with_cuda=with_cuda)
  File "F:\Anaconda\envs\py37\lib\site-packages\torch\utils\cpp_extension.py", line 922, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "F:\Anaconda\envs\py37\lib\site-packages\torch\utils\cpp_extension.py", line 1082, in _build_extension_module
    raise RuntimeError(message)
...
cl: 命令行 warning D9002 :忽略未知选项“-O3”
cl: 命令行 warning D9002 :忽略未知选项“-std=c++17”
注意: 包含文件:  g:\multi-obj\data\cnn\pvcnn-master\pvcnn-master\modules\functional\src\ball_query\ball_query.hpp
注意: 包含文件:   F:\Anaconda\envs\py37\lib\site-packages\torch\include\torch/extension.h
注意: 包含文件:    F:\Anaconda\envs\py37\lib\site-packages\torch\include\torch\csrc\api\include\torch/all.h
注意: 包含文件:     F:\Anaconda\envs\py37\lib\site-packages\torch\include\torch\csrc\api\include\torch/cuda.h
注意: 包含文件:      F:\Anaconda\envs\py37\lib\site-packages\torch\include\torch/csrc/WindowsTorchApiMacro.h
注意: 包含文件:       F:\Anaconda\envs\py37\lib\site-packages\torch\include\c10/macros/Export.h
注意: 包含文件:        F:\Anaconda\envs\py37\lib\site-packages\torch\include\c10/macros/cmake_macros.h
F:\Anaconda\envs\py37\lib\site-packages\torch\include\torch\csrc\api\include\torch/cuda.h(5): fatal error C1083: 无法打 开包括文件: “cstddef”: No such file or directory
[7/14] cl /showIncludes -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -IF:\Anaconda\envs\py37\lib\site-packages\torch\include -IF:\Anaconda\envs\py37\lib\site-packages\torch\include\torch\csrc\api\include -IF:\Anaconda\envs\py37\lib\site-packages\torch\include\TH -IF:\Anaconda\envs\py37\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\include" -IF:\Anaconda\envs\py37\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /EHsc -O3 -std=c++17 -c G:\multi-obj\data\CNN\pvcnn-master\pvcnn-master\modules\functional\src\interpolate\neighbor_interpolate.cpp /Foneighbor_interpolate.o
FAILED: neighbor_interpolate.o
cl /showIncludes -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -IF:\Anaconda\envs\py37\lib\site-packages\torch\include -IF:\Anaconda\envs\py37\lib\site-packages\torch\include\torch\csrc\api\include -IF:\Anaconda\envs\py37\lib\site-packages\torch\include\TH -IF:\Anaconda\envs\py37\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\include" -IF:\Anaconda\envs\py37\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /EHsc -O3 -std=c++17 -c G:\multi-obj\data\CNN\pvcnn-master\pvcnn-master\modules\functional\src\interpolate\neighbor_interpolate.cpp /Foneighbor_interpolate.o
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.16.27051 版
版权所有(C) Microsoft Corporation。保留所有权利。

cl: 命令行 warning D9002 :忽略未知选项“-O3”
cl: 命令行 warning D9002 :忽略未知选项“-std=c++17”
注意: 包含文件:  g:\multi-obj\data\cnn\pvcnn-master\pvcnn-master\modules\functional\src\interpolate\neighbor_interpolate.hpp
注意: 包含文件:   F:\Anaconda\envs\py37\lib\site-packages\torch\include\torch/extension.h
注意: 包含文件:    F:\Anaconda\envs\py37\lib\site-packages\torch\include\torch\csrc\api\include\torch/all.h
注意: 包含文件:     F:\Anaconda\envs\py37\lib\site-packages\torch\include\torch\csrc\api\include\torch/cuda.h
注意: 包含文件:      F:\Anaconda\envs\py37\lib\site-packages\torch\include\torch/csrc/WindowsTorchApiMacro.h
注意: 包含文件:       F:\Anaconda\envs\py37\lib\site-packages\torch\include\c10/macros/Export.h
注意: 包含文件:        F:\Anaconda\envs\py37\lib\site-packages\torch\include\c10/macros/cmake_macros.h
F:\Anaconda\envs\py37\lib\site-packages\torch\include\torch\csrc\api\include\torch/cuda.h(5): fatal error C1083: 无法打 开包括文件: “cstddef”: No such file or directory
[8/14] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\bin\nvcc -Xcompiler /EHsc -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -IF:\Anaconda\envs\py37\lib\site-packages\torch\include -IF:\Anaconda\envs\py37\lib\site-packages\torch\include\torch\csrc\api\include -IF:\Anaconda\envs\py37\lib\site-packages\torch\include\TH -IF:\Anaconda\envs\py37\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\include" -IF:\Anaconda\envs\py37\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=sm_75 -c G:\multi-obj\data\CNN\pvcnn-master\pvcnn-master\modules\functional\src\interpolate\trilinear_devox.cu -o trilinear_devox.cuda.o
FAILED: trilinear_devox.cuda.o
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\bin\nvcc -Xcompiler /EHsc -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -IF:\Anaconda\envs\py37\lib\site-packages\torch\include -IF:\Anaconda\envs\py37\lib\site-packages\torch\include\torch\csrc\api\include -IF:\Anaconda\envs\py37\lib\site-packages\torch\include\TH -IF:\Anaconda\envs\py37\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\include" -IF:\Anaconda\envs\py37\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=sm_75 -c G:\multi-obj\data\CNN\pvcnn-master\pvcnn-master\modules\functional\src\interpolate\trilinear_devox.cu -o trilinear_devox.cuda.o
F:/Anaconda/envs/py37/lib/site-packages/torch/include\c10/util/Exception.h(28): warning #1388-D: base class dllexport/dllimport specification differs from that of the derived class

Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"
...
F:/Anaconda/envs/py37/lib/site-packages/torch/include\c10/core/TensorTypeSet.h(44): warning #68-D: integer conversion resulted in a change of sign

F:/Anaconda/envs/py37/lib/site-packages/torch/include\c10/core/impl/LocalTensorTypeSet.h(50): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\c10/core/impl/LocalTensorTypeSet.h(51): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\c10/util/logging_is_not_google_glog.h(47): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\c10/core/TensorImpl.h(224): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\c10/core/TensorImpl.h(1560): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\c10/core/TensorImpl.h(1563): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\c10/core/TensorImpl.h(1585): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\c10/core/TensorImpl.h(1586): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\c10/core/TensorImpl.h(1611): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\c10/core/TensorImpl.h(1630): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/Generator.h(75): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/NamedTensor.h(53): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/TensorBody.h(1104): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/ivalue_inl.h(118): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/ivalue_inl.h(138): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/ivalue_inl.h(139): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/ivalue_inl.h(188): warning #1388-D: base class dllexport/dllimport specification differs from that of the derived class

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/ivalue_inl.h(200): warning #1388-D: base class dllexport/dllimport specification differs from that of the derived class

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/ivalue_inl.h(210): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/ivalue_inl.h(301): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/ivalue_inl.h(302): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/ivalue_inl.h(303): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/ivalue_inl.h(306): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/ivalue_inl.h(307): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/ivalue_inl.h(313): warning #1388-D: base class dllexport/dllimport specification differs from that of the derived class

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/ivalue_inl.h(389): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/ivalue_inl.h(390): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/jit_type.h(370): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/jit_type.h(617): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/jit_type.h(618): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/jit_type.h(621): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/jit_type.h(633): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/jit_type.h(748): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/jit_type.h(797): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/jit_type.h(879): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/jit_type.h(881): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/jit_type.h(1574): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/jit_type.h(1575): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/jit_type.h(1577): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/jit_type.h(1581): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/jit_type.h(1584): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/jit_type.h(1639): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/boxing/KernelFunction.h(375): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/boxing/KernelFunction.h(376): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/dispatch/Dispatcher.h(132): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/dispatch/Dispatcher.h(133): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/dispatch/Dispatcher.h(134): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/dispatch/Dispatcher.h(135): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/dispatch/Dispatcher.h(136): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/core/dispatch/Dispatcher.h(164): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/CPUGenerator.h(32): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/CPUGenerator.h(33): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/CPUGenerator.h(34): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/Context.h(124): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/Context.h(125): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/Context.h(130): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/Context.h(131): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/Context.h(132): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/TensorGeometry.h(56): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\ATen/TensorGeometry.h(57): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\c10/cuda/CUDAStream.h(171): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

vox.cu
nvcc error   : 'cudafe++' died with status 0xC00000FD (STACK_OVERFLOW)
[13/14] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\bin\nvcc -Xcompiler /EHsc -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -IF:\Anaconda\envs\py37\lib\site-packages\torch\include -IF:\Anaconda\envs\py37\lib\site-packages\torch\include\torch\csrc\api\include -IF:\Anaconda\envs\py37\lib\site-packages\torch\include\TH -IF:\Anaconda\envs\py37\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\include" -IF:\Anaconda\envs\py37\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=sm_75 -c G:\multi-obj\data\CNN\pvcnn-master\pvcnn-master\modules\functional\src\sampling\sampling.cu -o sampling.cuda.o
FAILED: sampling.cuda.o
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\bin\nvcc -Xcompiler /EHsc -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -IF:\Anaconda\envs\py37\lib\site-packages\torch\include -IF:\Anaconda\envs\py37\lib\site-packages\torch\include\torch\csrc\api\include -IF:\Anaconda\envs\py37\lib\site-packages\torch\include\TH -IF:\Anaconda\envs\py37\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\include" -IF:\Anaconda\envs\py37\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=sm_75 -c G:\multi-obj\data\CNN\pvcnn-master\pvcnn-master\modules\functional\src\sampling\sampling.cu -o sampling.cuda.o
F:/Anaconda/envs/py37/lib/site-packages/torch/include\c10/util/Exception.h(28): warning #1388-D: base class dllexport/dllimport specification differs from that of the derived class

Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

F:/Anaconda/envs/py37/lib/site-packages/torch/include\c10/util/Exception.h(29): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\c10/util/Exception.h(30): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\c10/util/Exception.h(35): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\c10/util/Exception.h(36): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\c10/core/Allocator.h(21): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\c10/core/Allocator.h(183): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\c10/util/typeid.h(460): warning #1390-D: dllexport/dllimport conflict with "caffe2::TypeMeta::_typeMetaDataInstance [with T=caffe2::detail::_Uninitialized]"
(456): here; dllexport assumed

F:/Anaconda/envs/py37/lib/site-packages/torch/include\c10/util/intrusive_ptr.h(63): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\c10/util/intrusive_ptr.h(64): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\c10/core/Storage.h(181): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\c10/core/TensorTypeSet.h(44): warning #68-D: integer conversion resulted in a change of sign

F:/Anaconda/envs/py37/lib/site-packages/torch/include\c10/core/impl/LocalTensorTypeSet.h(50): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\c10/core/impl/LocalTensorTypeSet.h(51): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\c10/util/logging_is_not_google_glog.h(47): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface

F:/Anaconda/envs/py37/lib/site-packages/torch/include\c10/core/TensorImpl.h(224): warning #1394-D: field of class type without a DLL interface used in a class with a DLL interface
...
sampling.cu
nvcc error   : 'cudafe++' died with status 0xC00000FD (STACK_OVERFLOW)
ninja: build stopped: subcommand failed.

**Comment by zhijian-liu** [comment]
This error seems to be related to your CUDA and PyTorch versions. We haven't tried this repo with newer versions.

**Comment by Xtian-hub** [comment]
您好，我是耿晓天我已经收到了您的来信，稍后我会回复，谢谢?7?8(?1?1ω?1?1)?1?7
