### ISSUE TITLE
Question about voxelization modul (compares to spvoxelize in torchsparse)

### ISSUE THREAD

**Issue by sIHURs** [mit-han-lab/pvcnn#81]
Hi~

I'm just starting to learn some deep learning concepts for point clouds. I have a project that requires voxelization as an operation, and I need to incorporate voxelization as a layer in a PyTorch model.

 Due to some environment issues, the modules from PVCNN have problems with import (even after running for a long time, the import is not successful). However, I successfully downloaded TorchSparse. I noticed that TorchSparse has a method torchsparse.nn.functional.spvoxelize that seems very similar to the voxelization module in PVCNN. The TorchSparse wiki does not provide information about the counts parameter, I'm not sure what it is. 

The question is, if I have coords, feats, and resolution, how can I use spvoxelize to get a voxelized output with the shape (b, c, resolution, resolution, resolution)?

thanks very much
yifan

**Comment by zhijian-liu** [comment]
@sIHURs, this repository is no longer actively maintained. Thanks for your interest in this work.
